/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each page of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'tutorial/index',
    {
      type: 'category',
      label: 'Incremental Tutorial',
      items: [
        'tutorial/level1-basics',
        'tutorial/level2-sequential',
        'tutorial/level3-parallel',
        'tutorial/level4-resilience',
        'tutorial/level5-advanced',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'getting-started/index',
        'examples/index',
        'troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'migration-prompt-guide',
      ],
    },
  ],
};

module.exports = sidebars;
