name: Build & Publish

on:
  push:
    branches:
      - develop-v2   # snapshots
      - main         # releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Publish to Maven Local
        run: |
          chmod +x ./gradlew
          ./gradlew clean publishToMavenLocal --no-daemon
        env:
          ORG_GRADLE_PROJECT_signing.key: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.SIGNING_PASSWORD }}

      # -----------------------------
      # Crear bundle automáticamente
      # -----------------------------
      - name: Create bundle
        run: |
          mkdir -p bundle
          find ~/.m2/repository/io/github/rrguez/flowforge -type f \
            \( -name "*.jar" -o -name "*.pom" -o -name "*.asc" -o -name "maven-metadata.xml" \) \
            -exec cp --parents {} bundle/ \;
          cd bundle
          zip -r ../bundle.zip .

      # -----------------------------
      # Publicar SNAPSHOT
      # -----------------------------
      - name: Publish Snapshot to Central
        if: github.ref == 'refs/heads/develop-v2'
        run: |
          curl -X POST "https://central.sonatype.com/api/v1/publisher/upload" \
            -H "Authorization: Bearer ${{ secrets.MAVEN_CENTRAL_TOKEN }}" \
            -F "bundle=@bundle.zip"

      # -----------------------------
      # Publicar RELEASE
      # -----------------------------
      - name: Publish Release to Central
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST "https://central.sonatype.com/api/v1/publisher/upload" \
            -u "${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_PASSWORD }}" \
            -F "bundle=@bundle.zip"
